//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbReader.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbReader.Tests.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	CustomerId,
        ///	CompanyName,
        ///	ContactName,
        ///	ContactTitle,
        ///	Address,
        ///    City,
        ///    Region,
        ///	PostalCode,
        ///    Country,
        ///    Phone,
        ///    Fax 
        ///FROM 
        ///	Customers
        ///.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	c.CustomerID as CustomerWithOrdersId,
        ///	o.OrderId as O_OrderId
        ///FROM 
        ///	Customers c
        ///INNER JOIN 
        ///	Orders o 
        ///ON 
        ///	c.CustomerId =o.CustomerId.
        /// </summary>
        internal static string CustomersAndOrders {
            get {
                return ResourceManager.GetString("CustomersAndOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH RECURSIVE ctx
        ///(
        ///    employeeid,   
        ///    reportsto
        ///)
        ///AS
        ///(
        ///    SELECT 
        ///        initial.employeeid,
        ///        initial.reportsto        
        ///    FROM            
        ///        employees initial  
        ///    UNION ALL
        ///    SELECT
        ///        emp.employeeid,
        ///        emp.reportsto        
        ///    FROM 
        ///        employees emp
        ///    INNER JOIN 
        ///        ctx on ctx.employeeid = emp.reportsto
        ///)    
        ///
        ///select     
        ///    r.Employeeid as EmployeeId,
        ///    r.FirstName as FirstName,
        ///    r.LastName as LastName,
        ///    e.Employeeid as  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmployeesHierarchy {
            get {
                return ResourceManager.GetString("EmployeesHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    e.EmployeeId,
        ///	e.LastName,
        ///	e.FirstName,
        ///    o.OrderId AS Orders_OrderId,
        ///	o.OrderDate as Orders_OrderDate,
        ///	NULL as Territories_id,
        ///	NULL as Territories_TerritoryDescription
        ///FROM 
        ///    Employees e
        ///INNER JOIN 
        ///    Orders o 
        ///ON 
        ///    e.EmployeeId = o.employeeId AND
        ///    e.EmployeeId = @EmployeeId 
        ///UNION
        ///SELECT 
        ///	e.EmployeeId,
        ///	e.LastName,
        ///	e.FirstName,
        ///	NULL AS Orders_OrderId,
        ///	NULL AS Orders_OrderDate,
        ///	t.TerritoryId as Territories_id,
        ///	t.TerritoryDescription as Territories_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmployeesWithOrdersAndTerritories {
            get {
                return ResourceManager.GetString("EmployeesWithOrdersAndTerritories", resourceCulture);
            }
        }
    }
}
